config/routes.rb
Rails.application.routes.draw do
  resources :gossip do
	resources :comment
	resources :likes
  end
  resources :user, only: [:new, :create, :show]
  resources :city, only: [:show]
  resources :session, only: [:new, :create, :destroy]
  resources :contacts, only: [:index]
  resources :team, only: [:index]

  root 'gossip#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users, dependent: :destroy
	validates :name, presence: true
	validates :zip_code, 
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[abAB]))[0-9]{3}\z/, message: "good zip code please" }
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	validates :content, presence:true	
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :users, through: :likes, dependent: :destroy
	has_many :join_table_tag_gossips, dependent: :destroy
	has_many :tags, through: :join_table_tag_gossips, dependent: :destroy
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { in: 3..14 }
    validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
	validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_tag_gossips, dependent: :destroy
	has_many :gossips, through: :join_table_tag_gossips, dependent: :destroy
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

	belongs_to :city, dependent: :destroy
	has_many :likes, dependent: :destroy
  has_many :gossips, through: :likes, dependent: :destroy
  has_many :gossips, dependent: :destroy
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "Message", dependent: :destroy
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "Message", dependent: :destroy
  has_many :comments, dependent: :destroy
  has_secure_password
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :description, presence:true
  validates :age, presence:true
  validates :city, presence:true
  validates :password, presence: true, length: {minimum: 6}

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
  end

  def show
    @city = City.find(params[:id])
    @gossips = []
    @city.users.each do |u|
      u.gossips.each do |g|
        @gossips << g 
      end
    end  
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
before_action :authenticate_user, only: [:new, :edit, :destroy]
before_action :verify_user_rights, only: [:edit, :destroy]

  def index
    @all_gossip = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments
    @comment = Comment.new
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(content: params[:content], title: params[:title], user: current_user) # current_user = User.find_by(id: session[:user_id]) dans session_helper
    
    if @gossip.save
      flash[:notice] = "Vous avez crée un potin avec succès"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
      @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    post_params = params[:gossip]
    
    if @gossip.update(content: post_params[:content], title: post_params[:title], user: current_user) # ou mettre params[:id] pour de garder le même auteur au choix...  current_user = User.find_by(id: session[:user_id]) dans session_helper
      flash[:notice] = "Vous avez mis-à-jour un potin avec succès"    
      redirect_to root_path
    else
      render 'edit'
    end

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy

    flash[:notice] = "Vous avez supprimé un potin avec succès"
    redirect_to root_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Merci de vous connecter"
      redirect_to new_session_path
    end
  end

  def verify_user_rights
    unless current_user == Gossip.find(params[:id]).user
      flash[:danger] = "Vous ne pouvez pas faire ça !!"
      redirect_to root_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :authenticate_user, only: [:new, :edit, :destroy]
before_action :find_gossip
before_action :find_like, only: [:destroy]

  def create
      if already_liked?
        flash[:notice] = "Tu ne peux pas liker plus d'une fois"
      else
       flash[:notice] = "Tu as liké comme un bosse!" 
       @gossip.likes.create(user_id: current_user.id)
       redirect_to gossip_path(params[:gossip_id])
      end
  end

   def destroy
     if !(already_liked?)
       flash[:notice] = "Tu ne peux pas enlever des coeurs comme ça..."
     else
       @like.destroy
       flash[:danger] = "Like pulvérisé"
   	end
   	  redirect_to gossip_path(params[:gossip_id])
   end

  private

  def find_gossip	
    @gossip = Gossip.find(params[:gossip_id])
  end

  def already_liked?
  Like.where(user_id: current_user.id, gossip_id:
  params[:gossip_id]).exists?
  end


   def find_like
    @like = @gossip.likes.find(params[:id])
   end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], password: params[:password], city: City.all.sample)
    
    #Verify if you have all the informations
     if @user.save # cf. user.rb >> model validations
       flash[:notice] = "Vous Vous êtes bien enregistré(e)!"
       log_in(@user) #cf. session_helper
       redirect_to root_path
     else
      flash.now[:danger] = 'Il manque des informations...'
      render 'new'      
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper
   
   def log_in(user)
    session[:user_id] = user.id
  end

  def remember (user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

   def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
   end

  def log_out
  	log_out(:user_id)
  	@current_user = nil
  	forget(current_user)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/gossip/create.html.erb
<h1>Gossip#create</h1>
<p>Find me in app/views/gossip/create.html.erb</p>

app/views/gossip/edit.html.erb
<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Gossip update process failed due to:</p>
      <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="header">
	<h1> Editer le Gossip numéro <%=@gossip.id%></h1>
</div>

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title'%>
    <%= f.text_field :content, class: 'form-control', placeholder: 'Content'%>
  </div>
  <div class="form-group">
	<button type="submit" class="btn btn-secondary"> Editer le potin </button>
  </div>
<% end %>

app/views/gossip/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
   <div class="notice"> 
   	 <%=flash[:notice] %> 
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
  </div>
<% end %>	

<% if flash[:danger] %>
  <div class="alert alert-danger" role="alert">
   <div class="notice"> 
   	 <%=flash[:danger] %> 
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
  </div>
<% end %>

<% if session[:user_id] != nil %>
<h2 class="d-flex justify-content-center mt-3">Bienvenue <%= current_user.first_name %> sur le Gossip Project</h2>
<div class="text-center">
<%= link_to "Ajoute un Gossip !!", new_gossip_path, class: "btn btn-info btn-lg mt-3"%>
</div>
<%else%>

<h2 class="d-flex justify-content-center mt-3">Bienvenue sur le Gossip Project</h2>
<div class="text-center">
<%= link_to "Connecte-toi !!", new_session_path, class: "btn btn-info btn-lg mt-3"%>
</div>

<%end%>

<div class="row mt-4">
	<% @all_gossip.each_with_index do |gossip, id| %>
	  <div class="card mx-auto mb-5" style="width: 15rem;">
		  <div class="card-body">
		    <h5 class="card-title"><%= gossip.user.first_name %> <%= gossip.user.last_name %></h5>
		    <p class="card-text"><%= gossip.title %></p>
		    <%= link_to "Voir le potin", gossip_path(gossip.id), :class => "btn btn-secondary"%>
		  </div>
      <div class="card-footer text-muted">
        Commentaires : <%= gossip.comments.count %></br>   
        Likes : <%= gossip.likes.count %> 
      </div>
	  </div>
	<% end %>
</div>

app/views/gossip/new.html.erb
<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Gossip creation process failed due to:</p>
      <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag url_for(action: 'create'), method: "post" do %>
  <%= text_field_tag 'title', '', class: 'form-control', placeholder: 'Title'%>
  <%= text_area_tag 'content', '', class: 'form-control', placeholder: 'Content'%>
  <%= submit_tag "Créer Potins", class: "btn btn-secondary" %>
<% end %>

app/views/gossip/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
   <div class="notice"> 
     <%=flash[:notice] %> 
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
  </div>
<% end %> 

<% if flash[:danger] %>
  <div class="alert alert-danger" role="alert">
   <div class="notice"> 
     <%=flash[:danger] %> 
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
  </div>
<% end %>


<div class="card text-center mt-3">
  <div class="card-header">
    <h1> Gossip numéro <%=params[:id]%></h1>
  </div>
  <div class="card-body">
	  <h4 class="card-title"><%= @gossip.user.first_name %> <%= @gossip.user.last_name %> </h4></br>
	  <h5 class="card-text"><%= @gossip.title %></h5>
	  <p class="card-text"><%= @gossip.content %></p>
	  <%= link_to "Editer le potin", edit_gossip_path(@gossip.id), class: "btn btn-secondary" %>
	  <%= link_to "Supprimer le gossip", gossip_path(@gossip.id), method: "delete", class: "btn btn-danger", data: { confirm: "Vous-êtes vraiment sur ?"}%>
  </div>
  <div class="card-footer text-muted">
	  Profil de l'auteur : <%= link_to @gossip.user.first_name, user_path(@gossip.user.id), class: "text-primary"  %></br>   
	  Ville de l'auteur : <%= link_to @gossip.user.city.name, city_path(@gossip.user.city.id), class: "text-primary"  %></br>
	  Date de création : <%= @gossip.created_at.strftime("%d/%m/%Y") %>	     
  </div>
</div>

<p><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>

<% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', gossip_like_path(params[:id], pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', gossip_likes_path(params[:id]), method: :post %>
<% end %>

<ul class="mt-3">
<% @gossip.comments.each_with_index do |comment, id| %>
  <li class="mt-1"><%= comment.user.first_name %> <%= comment.user.last_name %> : <%= comment.content %>
  <%= link_to "Edit", edit_gossip_comment_path(@gossip.id,comment.id), class: "text-secondary small"  %></li>
<% end %>
</ul>

 <div class="card m-5">
 <div class="card-header">
  <h1>Ajouter un commentaire</h1>
  </div>
  <%= form_tag(gossip_comment_index_path(params[:id]), method: :create) do %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="card-body text-secondary">
    <div class="form-group">
      <%= label_tag 'Contenu du commentaire' %>
      <%= text_area_tag 'content', @comment.content, class: "form-control", placeholder: "Ton commentaire" %>
      <br /> <br />

      <%= submit_tag "Ajouter un commentaire", class: "btn btn-secondary" %>
    <% end %>
  </div>
  </div>

</div>

app/views/gossip/update.html.erb
<h1>Gossip#update</h1>
<p>Find me in app/views/gossip/update.html.erb</p>