config/routes.rb
Rails.application.routes.draw do
  resources :gossip do
	resources :comment
	resources :likes
  end
  resources :user, only: [:new, :create, :show]
  resources :city, only: [:show]
  resources :session, only: [:new, :create, :destroy]
  resources :contacts, only: [:index]
  resources :team, only: [:index]

  root 'gossip#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users, dependent: :destroy
	validates :name, presence: true
	validates :zip_code, 
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[abAB]))[0-9]{3}\z/, message: "good zip code please" }
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	validates :content, presence:true	
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :users, through: :likes, dependent: :destroy
	has_many :join_table_tag_gossips, dependent: :destroy
	has_many :tags, through: :join_table_tag_gossips, dependent: :destroy
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { in: 3..14 }
    validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
	validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_tag_gossips, dependent: :destroy
	has_many :gossips, through: :join_table_tag_gossips, dependent: :destroy
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

	belongs_to :city, dependent: :destroy
	has_many :likes, dependent: :destroy
  has_many :gossips, through: :likes, dependent: :destroy
  has_many :gossips, dependent: :destroy
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "Message", dependent: :destroy
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "Message", dependent: :destroy
  has_many :comments, dependent: :destroy
  has_secure_password
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :description, presence:true
  validates :age, presence:true
  validates :city, presence:true
  validates :password, presence: true, length: {minimum: 6}

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
  end

  def show
    @city = City.find(params[:id])
    @gossips = []
    @city.users.each do |u|
      u.gossips.each do |g|
        @gossips << g 
      end
    end  
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], password: params[:password], city: City.all.sample)
    
    #Verify if you have all the informations
     if @user.save # cf. user.rb >> model validations
       flash[:notice] = "Vous Vous êtes bien enregistré(e)!"
       log_in(@user) #cf. session_helper
       redirect_to root_path
     else
      flash.now[:danger] = 'Il manque des informations...'
      render 'new'      
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper
   
   def log_in(user)
    session[:user_id] = user.id
  end

  def remember (user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

   def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
   end

  def log_out
  	log_out(:user_id)
  	@current_user = nil
  	forget(current_user)
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "THE GOSSIP PROJECT", root_path, class: "navbar-brand"%>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "New Gossip", new_gossip_path, class: "nav-item nav-link"%>
          <%= link_to "Team", team_index_path, class: "nav-item nav-link"%>
          <%= link_to "Contact", contacts_path, class: "nav-item nav-link"%>
          <%= link_to "Random", gossip_path(Gossip.all.sample.id), class: "nav-item nav-link"%>
        </div>
        <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
          
          <% if session[:user_id] != nil %>
            <div class="btn-group">
              <button type="button" class="btn btn-dark"><%= current_user.first_name %></button>
              <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
              </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to "Mon profil", user_path(current_user.id), class: "dropdown-item" %>
                
                <%= link_to "Se déconnecter", session_path(current_user.id), method: :delete, class: "dropdown-item", data: { confirm: "Quitter définitivement ?"} %>
                
              </div>
            </div>
          
          <%else%>
          <%= link_to "Se connecter / S'inscrire", new_session_path, class: "nav-item nav-link"%>
          <%end%>

        </div>  
        </div>
      </div>
    </nav>
    <div class="container-fluid">
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>